spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_ROOT_PASSWORD:dnwjd123}
      jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/${DATABASE_NAME:spring}
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 3
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_ROOT_PASSWORD:dnwjd123}
      jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/${DATABASE_NAME:spring}
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 2
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true