server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/appsdeveloperblog
#          issuer-uri: http://localhost8080/appsdeveloperblog
          jwk-set-uri: http://localhost:8080/realms/appsdeveloperblog/protocol/openid-connect/certs
